### ISSUE TITLE
创建采购计划/……/查询添加

### ISSUE THREAD

**Issue by aether1989** [TinderTeam/Fuego#18]
查询页面输入查询条件没有查询结果

**Comment by nanbowen** [comment]
I can't follow your main idea in this code: @tangjun114 
![image](https://f.cloud.github.com/assets/5795691/1466067/78c8119a-456b-11e3-9b28-75c5124162f4.png)
and then
![image](https://f.cloud.github.com/assets/5795691/1466077/880944bc-456b-11e3-97a7-370539ba6787.png)

why you try to get assetsList by a IDList instead of using Dao with Searchfilter?

**Comment by nanbowen** [comment]
We cancel this fuction . so foget it.
